package selldatabase;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author ASUS
 */
public class Detailed extends javax.swing.JFrame {
    public static double price2,kilometer2;
    public static String category2,name2,color2,brand2,accident2,phone2,email2;////////////////////////////////////////////////////ستتیکو بردار
    public Detailed(int a) {//a = 1 means chat button should be and a = 0 means that delete button should be
        initComponents();
        System.out.println("constructor of detailed started");//////////////////////////////////
        name.setText(name2);
        System.out.println("name");
        category1.setText(category2);
        System.out.println("name");
        price1.setText(Double.toString(price2));
        
        phone1.setText(phone2);
        System.out.println("name");
        color1.setText(color2);
        System.out.println("name");
        brand.setVisible(false);
        brand1.setVisible(false);
        kilometer.setVisible(false);
        kilometer1.setVisible(false);
        accident.setVisible(false);
        accident1.setVisible(false);
        back.setVisible(true);
        chat.setVisible(false);
        delete.setVisible(false);
        if(a == 1){
            chat.setVisible(true);
        }else{
            delete.setVisible(true);
        }
        if(category2.equals("Cars")){
            System.out.println("carEE");
            brand1.setText(brand2);
            System.out.println("name");
            kilometer1.setText(Double.toString(kilometer2));
            System.out.println("name");
            accident1.setText(accident2);
            System.out.println("name");
            brand.setVisible(true);
            brand1.setVisible(true);
            kilometer.setVisible(true);
            kilometer1.setVisible(true);
            accident.setVisible(true);
            accident1.setVisible(true);
        }
        if(category2.equals("Electronics")){
            brand1.setText(brand2);
            brand.setVisible(true);
            brand1.setVisible(true);            
        }
        this.setVisible(true);
    }
    public void Detailed(){
        Ad c = new VehicleAd();
        this.name2=c.getName();
        this.category2 = c.getCategory();
        this.phone2 = c.getPhone();
        this.price2 = c.getPrice();
        this.color2= c.getColor();
        this.brand2 = c.getBrand();
        this.kilometer2 = c.getKilometer();
        this.accident2 = c.getAccident();
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        name = new javax.swing.JLabel();
        category = new javax.swing.JLabel();
        price = new javax.swing.JLabel();
        brand = new javax.swing.JLabel();
        color = new javax.swing.JLabel();
        phone = new javax.swing.JLabel();
        kilometer = new javax.swing.JLabel();
        accident = new javax.swing.JLabel();
        category1 = new javax.swing.JLabel();
        price1 = new javax.swing.JLabel();
        phone1 = new javax.swing.JLabel();
        color1 = new javax.swing.JLabel();
        brand1 = new javax.swing.JLabel();
        kilometer1 = new javax.swing.JLabel();
        accident1 = new javax.swing.JLabel();
        chat = new javax.swing.JButton();
        back = new javax.swing.JButton();
        delete = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        name.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        name.setText("jLabel1");

        category.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        category.setText("Category :");

        price.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        price.setText("Price :");

        brand.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        brand.setText("Brand&Model :");

        color.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        color.setText("Color :");

        phone.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        phone.setText("owner's phone number :");

        kilometer.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        kilometer.setText("Kilometers :");

        accident.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        accident.setText("Accident record :");

        category1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        category1.setText("jLabel1");

        price1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        price1.setText("jLabel2");

        phone1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        phone1.setText("jLabel3");

        color1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        color1.setText("jLabel4");

        brand1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        brand1.setText("jLabel5");

        kilometer1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        kilometer1.setText("jLabel6");

        accident1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        accident1.setText("jLabel7");

        chat.setText("Chat");
        chat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chatActionPerformed(evt);
            }
        });

        back.setText("Back");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });

        delete.setText("Delete");
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(kilometer)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(phone)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(56, 56, 56)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(brand)
                                        .addComponent(price)
                                        .addComponent(category)
                                        .addComponent(color))))
                            .addComponent(accident)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(chat)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(category1, javax.swing.GroupLayout.DEFAULT_SIZE, 221, Short.MAX_VALUE)
                            .addComponent(price1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(phone1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(color1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(brand1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(kilometer1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(accident1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(back)
                        .addGap(28, 28, 28)
                        .addComponent(delete)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(176, Short.MAX_VALUE)
                .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(84, 84, 84))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(category)
                    .addComponent(category1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(price)
                    .addComponent(price1))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(phone)
                    .addComponent(phone1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(color)
                    .addComponent(color1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(brand)
                    .addComponent(brand1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(kilometer)
                    .addComponent(kilometer1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(accident)
                    .addComponent(accident1))
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chat)
                    .addComponent(back)
                    .addComponent(delete))
                .addContainerGap(46, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void chatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chatActionPerformed
        
        Connections ob = new Connections();
        if(!ob.searchInsideChat(ManageAccount.Email, email2, 1)){
            ob.createChat(ManageAccount.Email, email2);
        }else{
            new shortMassages("Chat already exists").setVisible(true);
        }
    }//GEN-LAST:event_chatActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        
        this.dispose();
    }//GEN-LAST:event_backActionPerformed

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
        Connections ob = new Connections();
        ob.Delete(name2);
        this.dispose();
    }//GEN-LAST:event_deleteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Detailed.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Detailed.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Detailed.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Detailed.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel accident;
    private javax.swing.JLabel accident1;
    private javax.swing.JButton back;
    private javax.swing.JLabel brand;
    private javax.swing.JLabel brand1;
    private javax.swing.JLabel category;
    private javax.swing.JLabel category1;
    private javax.swing.JButton chat;
    private javax.swing.JLabel color;
    private javax.swing.JLabel color1;
    private javax.swing.JButton delete;
    private javax.swing.JLabel kilometer;
    private javax.swing.JLabel kilometer1;
    private javax.swing.JLabel name;
    private javax.swing.JLabel phone;
    private javax.swing.JLabel phone1;
    private javax.swing.JLabel price;
    private javax.swing.JLabel price1;
    // End of variables declaration//GEN-END:variables
}
