package selldatabase;

import java.util.ArrayList;
import java.util.List;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author ASUS
 */
public class ViewAnnouncements extends javax.swing.JFrame {

    /**
     * Creates new form ViewAnnouncements
     */
    public ViewAnnouncements() {
        initComponents();
            rangeCar.setVisible(false);
            CarCambo.setVisible(false);
            rangeElectronics.setVisible(false);
            ElectronicCambo.setVisible(false);
            rangeFurniture.setVisible(false);
            FurnitureCombo.setVisible(false);
            jButton1.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jPopupMenu2 = new javax.swing.JPopupMenu();
        jToggleButton1 = new javax.swing.JToggleButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        rangeCar = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        CarCambo = new javax.swing.JComboBox<>();
        ElectronicCambo = new javax.swing.JComboBox<>();
        rangeElectronics = new javax.swing.JLabel();
        FurnitureCombo = new javax.swing.JComboBox<>();
        rangeFurniture = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jToggleButton1.setText("jToggleButton1");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("To show you the best announcements please complete the following");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Category :");

        rangeCar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        rangeCar.setText("Price range:");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cars", "Electronics", "Furniture", "Toys", "Other" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        CarCambo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "+30000", "10000 to 30000", "5000 to 10000", "3000 to 5000", "less than 3000" }));

        ElectronicCambo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "+8000", "1000 to 8000", "500 to 1000", "100 to 500", "-100" }));

        rangeElectronics.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        rangeElectronics.setText("Price range:");

        FurnitureCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "+3000", "1000 to  3000", "400 to 1000", "less than 400" }));

        rangeFurniture.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        rangeFurniture.setText("Price range:");

        jButton1.setText("View");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(rangeCar)
                            .addComponent(jLabel2)
                            .addComponent(rangeElectronics)
                            .addComponent(rangeFurniture))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(FurnitureCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(CarCambo, 0, 315, Short.MAX_VALUE)
                            .addComponent(ElectronicCambo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(239, 239, 239)
                        .addComponent(jButton1)))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rangeCar)
                    .addComponent(CarCambo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ElectronicCambo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rangeElectronics))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FurnitureCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rangeFurniture))
                .addGap(33, 33, 33)
                .addComponent(jButton1)
                .addContainerGap(127, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        String category = (String) jComboBox1.getSelectedItem();
        if(category.equals("Cars")){
            rangeCar.setVisible(true);
            CarCambo.setVisible(true);
            jButton1.setVisible(true);
            return;
        }else if(category.equals("Electronics")){
            rangeElectronics.setVisible(true);
            ElectronicCambo.setVisible(true);
            jButton1.setVisible(true); 
            return;
        }else if (category.equals("Furniture")){
            rangeFurniture.setVisible(true);
            FurnitureCombo.setVisible(true);
            jButton1.setVisible(true);
            return;
        }else if(category.equals("Toys")){
            //
            jButton1.setVisible(true);
            return;
        }else {
            //
            jButton1.setVisible(true);
            return;
        }
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        VIEW.ownersEmails.clear();
        System.out.println("vieu announcements view Button1ActionPerformedEEEEEEEEEEEEEEEEEEEEEEEEEE");
        String category = (String) jComboBox1.getSelectedItem();
        System.out.println("category is "+ category);
        List<String> display = new ArrayList<>();
        Connections ob = new Connections();
        if(category.equals("Cars")){
            
            String range = (String) CarCambo.getSelectedItem();
            if(range.equals("+30000")){
                display = ob.searchInsideAds(category, 1000000, 30000);
                System.out.println("jButton1ActionPerformedhhhhhhhhhhhhhhhhhEEEEEEEEEEE");
            }else if(range.equals("10000 to 30000")){
                display = ob.searchInsideAds(category, 30000, 10000);
            }else if(range.equals("5000 to 10000")){
                display = ob.searchInsideAds(category, 10000, 5000);
            }else if(range.equals("3000 to 5000")){
                display = ob.searchInsideAds(category, 5000, 3000);
            }else {
                display = ob.searchInsideAds(category, 3000, 0);
            }
            VIEW view = new VIEW(display, 1);
             view.setVisible(true);
        }else if(category.equals("Electronics")){
            String range = (String) ElectronicCambo.getSelectedItem();
            if(range.equals("+8000")){
                display = ob.searchInsideAds(category, 100000, 8000);
            }else if(range.equals("1000 to 8000")){
                display = ob.searchInsideAds(category, 8000, 1000);
            }else if(range.equals("500 to 1000")){
                display = ob.searchInsideAds(category, 1000, 500);
            }else if(range.equals("100 to 500")){
                display = ob.searchInsideAds(category, 500, 100);
            }else {
                display = ob.searchInsideAds(category, 100, 0);
            }
            VIEW view = new VIEW(display, 1);
             view.setVisible(true);            
        }else if (category.equals("Furniture")){
            String range = (String) FurnitureCombo.getSelectedItem();
            if(range.equals("+3000")){
                display = ob.searchInsideAds(category, 100000, 3000);
            }else if(range.equals("1000 to 3000")){
                display = ob.searchInsideAds(category, 3000, 1000);
            }else if(range.equals("400 to 1000")){
                display = ob.searchInsideAds(category, 1000, 400);
            }else {
                display = ob.searchInsideAds(category, 400, 0);
            }
            VIEW view = new VIEW(display, 1);
             view.setVisible(true);
        }else if(category.equals("Toys")){
            display = ob.searchInsideAds(category, 100000, 0);
            VIEW view = new VIEW(display, 1);
             view.setVisible(true);
        }else {
            display = ob.searchInsideAds(category, 100000, 0);
            VIEW view = new VIEW(display, 1);
             view.setVisible(true);
        }
        
        //view.show();
       
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewAnnouncements.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewAnnouncements.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewAnnouncements.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewAnnouncements.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewAnnouncements().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CarCambo;
    private javax.swing.JComboBox<String> ElectronicCambo;
    private javax.swing.JComboBox<String> FurnitureCombo;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JPopupMenu jPopupMenu2;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JLabel rangeCar;
    private javax.swing.JLabel rangeElectronics;
    private javax.swing.JLabel rangeFurniture;
    // End of variables declaration//GEN-END:variables
}
